---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers

- name: Create In-Memory Inventory
  hosts: jumpbox
  gather_facts: true
  become: true
  #roles:
  #  - { role: "osp-facts"}
  tasks:
    - name: We are deploying in QA - Gather Facts and Generate In-Memory Inventory
      import_tasks: "./roles/osp-facts/tasks/main.yml"
      when: deploy_qa == True
      tags: qa

- name: Initial Configuration
  hosts: all:!jumpbox
  gather_facts: true 
  become: true
  roles:
    - { role: "configuration", tags: base-config }

- name: Deploy Database
  hosts: appdbs
  gather_facts: true
  roles:
    - { role: geerlingguy.postgresql, tags: [dbs, postgres] }

- name: Deploy Tomcat and httpd
  hosts: apps
  gather_facts: false
  become: true
  roles:
    - { role: app, tags: [apps, tomcat] }

- name: Deploy Frontend
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - { role: "frontend", tags: [lbs, haproxy] }

- name: Execute Smoke Test at the End
  hosts: 127.0.0.1
  gather_facts: false
  become: false
  #roles:
  #  - { role: "smoke_test", tags: smoke_test }
  tasks:
    - name: Run Smoke Test After Deployment
      import_tasks: "./roles/smoke_test/tasks/main.yml"
      delegate_to: jumpbox
      tags: smoke_test
